-- ============================================================================
-- 02_RAW_TABLES.SQL - Domain-specific typed table schemas
-- ============================================================================
USE DATABASE RENEWABLE_WIND;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.PLANTS (
  PLANT_ID VARCHAR(20) NOT NULL, PLANT_NAME VARCHAR(200), PROVINCE VARCHAR(50), PLANT_TYPE VARCHAR(30), CAPACITY FLOAT, UNIT VARCHAR(20), STATUS VARCHAR(20), COMMISSIONED_DATE DATE, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.GENERATION_LOGS (
  LOG_ID VARCHAR(30) NOT NULL, PLANT_ID VARCHAR(20), LOG_DATE TIMESTAMP, GENERATION_MWH FLOAT, CAPACITY_MW FLOAT, CAPACITY_FACTOR FLOAT, IRRADIANCE_KWH_M2 FLOAT, WIND_SPEED_MS FLOAT, CURTAILMENT_MWH FLOAT, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.EQUIPMENT (
  EQUIPMENT_ID VARCHAR(20) NOT NULL, EQUIPMENT_NAME VARCHAR(200), LINE_ID VARCHAR(20), EQUIPMENT_TYPE VARCHAR(50), STATUS VARCHAR(20), UPTIME_TARGET FLOAT, LAST_PM_DATE DATE, NEXT_PM_DATE DATE, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.GRID_DISPATCH (
  DISPATCH_ID VARCHAR(30) NOT NULL, PLANT_ID VARCHAR(20), DISPATCH_DATE TIMESTAMP, DISPATCHED_MW FLOAT, PRICE_PER_MWH FLOAT, GRID_FREQUENCY_HZ FLOAT, STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
