-- Generated from generator/demo_specs/aws-vietnam-renewable-wind.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-vietnam-renewable-wind
-- This is the schema that is actually deployed for VIETNAM_RENEWABLE_WIND.

-- Alerts fire on the bottom tail of Wind Generation
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_WIND_GENERATION) AS T
  FROM RAW.METRICS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_WIND_GENERATION <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_WIND_GENERATION), 2) AS AVG_WIND_GENERATION,
  ROUND(AVG(f.KPI_AVAILABILITY), 2) AS AVG_AVAILABILITY,
  ROUND(AVG(f.KPI_AVG_WIND_SPEED), 2) AS AVG_WIND_SPEED
FROM RAW.METRICS f
JOIN RAW.DOCUMENTS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_WIND_GENERATION), 2) AS AVG_WIND_GENERATION,
  ROUND(AVG(f.KPI_AVAILABILITY), 2) AS AVG_AVAILABILITY,
  ROUND(AVG(f.KPI_AVG_WIND_SPEED), 2) AS AVG_WIND_SPEED
FROM RAW.METRICS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_WIND_GENERATION) AS KPI_WIND_GENERATION, AVG(KPI_AVAILABILITY) AS KPI_AVAILABILITY, AVG(KPI_AVG_WIND_SPEED) AS KPI_AVG_WIND_SPEED FROM RAW.METRICS),
     en AS (SELECT SUM(KPI_CAPACITY_FACTOR) AS KPI_CAPACITY_FACTOR, SUM(KPI_TURBINES_ACTIVE) AS KPI_TURBINES_ACTIVE, SUM(KPI_WAKE_LOSS) AS KPI_WAKE_LOSS, SUM(KPI_PITCH_FAULTS_MTD) AS KPI_PITCH_FAULTS_MTD FROM RAW.DOCUMENTS)
  SELECT 1 AS SORT_ORDER, 'Wind Generation' AS TITLE, KPI_WIND_GENERATION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_WIND_GENERATION), 1) AS DECIMAL(38,1))) || ' ' || 'TWh' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Availability' AS TITLE, KPI_AVAILABILITY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AVAILABILITY), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Capacity Factor' AS TITLE, KPI_CAPACITY_FACTOR AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CAPACITY_FACTOR)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Turbines Active' AS TITLE, KPI_TURBINES_ACTIVE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_TURBINES_ACTIVE)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Avg Wind Speed' AS TITLE, KPI_AVG_WIND_SPEED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AVG_WIND_SPEED), 1) AS DECIMAL(38,1))) || ' ' || 'm/s' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Wake Loss' AS TITLE, KPI_WAKE_LOSS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_WAKE_LOSS)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Pitch Faults (MTD)' AS TITLE, KPI_PITCH_FAULTS_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PITCH_FAULTS_MTD)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
